---
inherit_from:
  - disabled_cops.yml

AllCops:
  DisplayCopNames: true
Rails:
  Enabled: true

##
# Cops that are excluding a specific folder, or enforce a non default style
#

Style/Alias:
  Description: Use alias_method instead of alias in a class or module body.
  EnforcedStyle: prefer_alias_method

Style/AccessModifierIndentation:
  Description: Indent private/protected/public as deep as method definitions
  Enabled: true
  EnforcedStyle: outdent

Style/HashSyntax:
  Description: 'Prefer Ruby 1.8 hash syntax { :a => 1, :b => 2 } over 1.9 syntax {
    a: 1, b: 2 }.'
  Enabled: true
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  Enabled: true
  EnforcedStyle: double_quotes
