---
inherit_from:
  - disabled_cops.yml

AllCops:
  RunRailsCops: true # include Rails cops
  DisplayCopNames: true

##
# Cops that are excluding a specific folder, or enforce a non default style
#

Style/AccessModifierIndentation:
  Description: Indent private/protected/public as deep as method definitions
  Enabled: true
  EnforcedStyle: outdent

Style/HashSyntax:
  Description: 'Prefer Ruby 1.8 hash syntax { :a => 1, :b => 2 } over 1.9 syntax {
    a: 1, b: 2 }.'
  Enabled: true
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  Enabled: true
  EnforcedStyle: double_quotes
